# Generated by cpp11: do not edit by hand

dijkstra_with_branches <- function(adj, edge_weights, branch_degrees, start_node_r, n_nodes) {
  .Call(`_pavement_dijkstra_with_branches`, adj, edge_weights, branch_degrees, start_node_r, n_nodes)
}
