# Generated by cpp11: do not edit by hand

dijkstra_with_branches_cpp <- function(adj, edge_weights, branch_degrees, start_node_r, n_nodes) {
  .Call(`_pavement_dijkstra_with_branches_cpp`, adj, edge_weights, branch_degrees, start_node_r, n_nodes)
}

sample_points_cpp <- function(sfc_linestrings, segment_length) {
  .Call(`_pavement_sample_points_cpp`, sfc_linestrings, segment_length)
}

split_linestrings_cpp <- function(sfc_linestrings, sfc_split_points, tolerance) {
  .Call(`_pavement_split_linestrings_cpp`, sfc_linestrings, sfc_split_points, tolerance)
}
