#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom graphics axis
#' @importFrom graphics par
#' @importFrom graphics segments
#' @importFrom grDevices heat.colors
#' @importFrom igraph as_edgelist
#' @importFrom igraph E
#' @importFrom igraph E<-
#' @importFrom igraph ends
#' @importFrom igraph graph_from_data_frame
#' @importFrom igraph is_directed
#' @importFrom igraph make_line_graph
#' @importFrom igraph V
#' @importFrom igraph V<-
#' @importFrom lwgeom st_endpoint
#' @importFrom lwgeom st_split
#' @importFrom lwgeom st_startpoint
#' @importFrom osmdata add_osm_feature
#' @importFrom osmdata opq
#' @importFrom osmdata osmdata_sf
#' @importFrom sf st_agr
#' @importFrom sf st_as_sf
#' @importFrom sf st_boundary
#' @importFrom sf st_cast
#' @importFrom sf st_centroid
#' @importFrom sf st_collection_extract
#' @importFrom sf st_contains
#' @importFrom sf st_coordinates
#' @importFrom sf st_crop
#' @importFrom sf st_crs
#' @importFrom sf st_distance
#' @importFrom sf st_drop_geometry
#' @importFrom sf st_equals
#' @importFrom sf st_intersection
#' @importFrom sf st_is_empty
#' @importFrom sf st_length
#' @importFrom sf st_line_sample
#' @importFrom sf st_linestring
#' @importFrom sf st_nearest_feature
#' @importFrom sf st_point
#' @importFrom sf st_reverse
#' @importFrom sf st_set_agr
#' @importFrom sf st_sf
#' @importFrom sf st_sfc
#' @importFrom sf st_transform
## usethis namespace: end
NULL
